<?php

namespace app\themes\assets\ds;

use Yii;
use yii\web\AssetBundle;
use dssource\basic\core\Themes;

class BasicAsset extends AssetBundle
{
    public $sourcePath;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = Themes::activeThemeRootPath().'/res/general';
    }

    public $css = [
        'css/bootstrap-theme.css',
        'css/multiNavBar.css',
    ];
    public $js = [
        'js/multiNavBar.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
    ];
}
